
### PATHS ###

# directory of genomic fasta sequences with .fna extension
genomes: resources/test_data/genomes

# directory of annotations with .gff extension
annotations: resources/test_data/annotations

# table of matching genome and annotation files
data_table:

# custom scratch directory (default is system default)
scratch:

# output data directories
filtered_genomes: results/genomes_filtered
filtered_annotations: results/annotations_filtered
proteins: results/proteins
functions: results/functions  #remove output directory when no functions should be run
statistics: results/statistics
metadata: results/metadata

### PARAMETERS ###

# minimum sequence length for the genomic fasta
min_len: 1000

# only keep features of longest isoform
longest_isoform: False

# minimum size of the CDS open reading frame
orf_size: 30

# comma separated list of InterProScan analyses
applications: "TIGRFAM,Pfam"
